alias cd..='cd ..'
alias ..='cd ..'
alias ~='cd ~'
alias short='USERDISPLAY=$SHORTNAME;HOSTDISPLAY=$SHORTHOST'
alias long='USERDISPLAY=$LONGNAME;HOSTDISPLAY=$LONGHOST'
alias bat='batcat'
alias python='python3'
alias playgba='VisualBoyAdvance -4 --save-flash --flash-128k --rtc --show-speed-normal --no-auto-frameskip'
