matches:
  - trigger: "find-dir"
    replace: "find . -type d -name [[directory]]"

  - trigger: "find-file"
    replace: "find . -type f -name [[file]]"

  - trigger: "ffmpeg-trim"
    replace: "ffmpeg -ss [[start]] -i [[input]] -to [[end]] -c copy [[output]]"

  - trigger: "gti"
    replace: "git"

  - trigger: "comit"
    replace: "commit"

  - trigger: "commmit"
    replace: "commit"
