matches:
  - trigger: "find-dir"
    form: "find . -type d -name [[directory]]"

  - trigger: "find-file"
    form: "find . -type f -name [[file]]"

  - trigger: "ffmpeg-trim"
    form: "ffmpeg -i [[input]] -ss [[start]] -to [[end]] -c copy [[output]]"

  - trigger: ":weather"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl wttr.in/?format=%l:+%c+%t"
